pyfar/sofar

- requirements_dev.txt
Required for read the docs to build via Sphinx.
Linked to #3
> Add missing dependencies in requirements_dev

- docs/examples.rst
- sofar/sofar.py
- tests/test_sofar.py
Add class function `Sofa.inspect` to inspect the data inside a SOFA file. This is in contrast to `Sofa.info` which outputs general information about the Convention of a SOFA file. The latter is needed when writing data, the new function is helpful when working with existing data.
> Add Sofa.inspect

- docs/sofar.rst
Minor bug, does not occur on the current main branch.
Required for merging #34, as build will fail otherwise.
> Fix import error occuring in autodoc

- sofar/sofa.py
- tests/test_sofa_verify.py
AES69-2022 will restrict the names of custom data. This new rule is added and tested:
Custom data can not have the same name as a variable or attribute contained in the respective convention.
> Update verification rules

- sofar/io.py
- tests/test_io.py
Leave version as it is by default when writing data but warn, if the version is outdated
> more careful writing defaults

- .circleci/config.yml
Test building the Sphinx documentation
This will not check if the generated HTML documents are valid nor will it validate against a reference.
It will merely fail on:
- broken example code
- Sphinx build errors
Building the docs on CircleCI required adding about 400 megabytes of latex packages.
It's probably better to add them to the Docker container in the future. This probably requires a custom one though.
> Test if sphinx build is succesful on CircleCI

- sofar/sofa.py
- tests/test_sofa_verify.py
sofar now issues a warning if creating, reading, or writing data with a convention version < 1.0
> Issue warning for preliminary conventions

- .readthedocs.yml
The old config style does not support setting python versions >= 3.9
The main branch uses version 3.7, which is still supported.
Documentation for this branch:
https://sofar.readthedocs.io/en/bugfix-rtd_config_update/
> Read the docs config update

- sofar/__init__.py
- sofar/io.py
- sofar/update_conventions.py
- sofar/utils.py
- use list constructor instead of loops and list comprehensions
- use contextlib to suppress exceptions
- use f-strings instead of string concatenations
Judging by the time it takes to run the tests, this improves performance by a bit, but not much. Also made parts of the code more compact.
> Refactorings for road to 1.0 PR

- sofar/update_conventions.py
- tests/test_utils.py
This should not raise an error, because Sofatoolbox master might not reflect the latest development state
> Raise warning in case of diverging conventions across platforms

- sofar/__init__.py
- sofar/io.py
- sofar/sofa.py
- sofar/utils.py
- tests/test_io.py
- tests/test_sofa.py
- tests/test_sofa_verify.py
- tests/test_utils.py
> Add a general `read_netcdf` function to read corrupted SOFA data

- sofar/io.py
- tests/test_io.py
make `sofar.io.read` and `sofar.io.write` accept path objects
closes #55 and https://github.com/pyfar/pyfar/issues/437
> Adjust io functions and tests for path objects

- README.rst
``pip install -e .`` did not work on develop, due to special characters, its fixes now
> fix readme for Contribution procedure

- .circleci/config.yml
- .readthedocs.yml
- docs/conf.py
- docs/examples.rst
- docs/index.rst
- docs/resources/conventions.py
- docs/resources/conventions.rst
- sofar/sofa.py
- tests/test_deprecations.py
closes #54 
Changes
Changes in the documentation:
https://sofar.readthedocs.io/en/feature-conventions_to_docs/resources/conventions.html
https://sofar.readthedocs.io/en/feature-conventions_to_docs/examples.html
> Include conventions in docs

- .circleci/config.yml
- .readthedocs.yml
- CONTRIBUTING.rst
- HISTORY.rst
- README.rst
- docs/conf.py
- docs/examples.rst
- docs/index.rst
- docs/resources/conventions.py
- docs/resources/conventions.rst
- setup.py
- sofar/__init__.py
- sofar/io.py
- sofar/sofa.py
- sofar/update_conventions.py
- sofar/utils.py
- tests/test_deprecations.py
- tests/test_io.py
- tests/test_sofa.py
- tests/test_sofa_upgrade_conventions.py
- tests/test_sofa_verify.py
- tests/test_utils.py
* Deprecate FreeFieldDirectivityTV 1.0 in favor of FreeFieldDirectivityTV 1.1 (according to sofaconventoins.org and AES69-2022)
* Add `sofar.read_sofa_as_netcdf` for reading SOFA files with erroneous data
* Document SOFA conventions on https://sofar.readthedocs.io/en/stable/resources/conventions.html. `Sofa.info()` will this be deprecated in sofar v1.3.0
* `sofar.read_sofa` and `sofar.write_sofa` now accept filenames and path objects
* Add testing for Python 3.11
> Release v.1.1.0

- CONTRIBUTING.rst
- README.rst
- docs/_templates/navbar-nav.html
- docs/working_with_sofa_files.rst
- sofar/sofa.py
We're often linking to the latest version of the docs, which points to the latest commit on the main branch.
This is replaced with the stable version, which is the latest tagged commit.
> Replace latest with stable when linking to parts of the docs

- sofar/update_conventions.py
Closes #84 
Updated parsing data from the SOFAtoolbox html. I looked into cloning instead, but there seems to be no way to clone a single folder and I did not want to clone the entire 64 MB repo every time that the testing is ran: ['Note that this will still download the whole repository from the server – only the checkout is reduced in size. At the moment it is not possible to clone only a single directory.'](https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository)
> Update parsing of csv files from github/SOFAtoolbox

- sofar/sofa.py
- tests/test_sofa_verify.py
This is required because `np.float_` will be deprecated in numpy 2.0 on 16. June 2023. It took the opportunity to improve the structure of the checks, improve the comments, and unify the error messages
> Bugfix for numpy>=2.0

- sofar/update_conventions.py
- tests/test_utils.py
closes #28
- First download conventions, then notify about potential changes and ask wheter or not to procede. Before this change conventions were downloaded and updated at the same time. This is more comfortable for just checking if there are updates without updating, which is nice for developing sofar
- Update and improve testing
> Separately download and update conventions

- sofar/io.py
Remove the explicit ascii encoding for string variables when writing SOFA files. It is not required because the string data is read with ascii encoding when reading SOFA files (see `value = chartostring(value, encoding="ascii")` in sofar.io.py). In addition it is causing compatability issues with the Matlab SOFAToolbox, because it is writing `*__Encoding` variables that are ignored by the Python NETCDF API but not by the Matlab NETCDF API. The `*__Encoding` variables show up when reading SOFA files with Matlab and raise an error when trying to write such data with Matlab.
No new tests required. I did an additional manual check and could not find any differences in files written with and without explicit ascii encoding of string variables.
> Remove explicit ascii encoding

- .github/ISSUE_TEMPLATE.md
- .github/workflows/has_label.yml
- .github/workflows/has_version_milestone.yml
- docs/conf.py
- pyproject.toml
apply latest cookiecuuter,
See https://github.com/pyfar/pyfar/pull/789
> apply cookiecutter

- pyproject.toml
Closes #126
- It adds packaging to dependencies, which got lost when we switched to pyproject.toml.
- Apparently, it is installed by default with conda, so we did not notice it before.
- I checked for other missing packages, but found nothing
> add packaging to dependencies
